name: Update dailydata.json
run-name: Update dailies

on:
  schedule:
    - cron: "5 0 * * *"

jobs:
  Update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run update
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          npm install axios
          npm run update
      - name: Push changes
        run: |
          git config --global user.email ${{ secrets.MAIL }}
          git config --global user.name "toarch7"
          git add dailydata.json
          git add weeklydata.json
          git commit --allow-empty -m "Daily Update"
          git push https://toarch7:${{ secrets.API_TOKEN_GITHUB }}@github.com/toarch7/torcherdev
